routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\APIController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PostController;
use App\Models\Settings as ModelSettings;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TrashMailController;
use App\Http\Controllers\Settings\AdsController;
use App\Http\Controllers\Settings\SeoController;
use App\Http\Controllers\Settings\SmtpController;
use App\Http\Controllers\Settings\GeneralController;
use App\Http\Controllers\Settings\ProfileController;
use App\Http\Controllers\Settings\BlogSettingController;

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('/update', [DashboardController::class, 'update'])->name('update');

    Route::get('/', function () {
        return to_route('dashboard');
    })->name('admin');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/settings', [DashboardController::class, 'settings'])->name('settings');

    // General Settings
    Route::get('/settings/general', [GeneralController::class, 'index'])->name('settings.general');
    Route::post('/settings/general/update', [GeneralController::class, 'update'])->name('settings.general.update');
    Route::post('/settings/general/update2', [GeneralController::class, 'update2'])->name('settings.general.update2');
    Route::post('/settings/check/imap', [GeneralController::class, 'check_imap'])->name('check.imap');

    // Seo Settings
    Route::get('/settings/seo', [SeoController::class, 'index'])->name('settings.seo');
    Route::post('/settings/seo/update', [SeoController::class, 'update'])->name('settings.seo.update');

    Route::get('/settings/license', [GeneralController::class, 'license'])->name('settings.license');
    Route::post('/settings/license/update', [GeneralController::class, 'license_update'])->name('settings.license.update');

    // Ads Settings
    Route::get('/settings/ads', [AdsController::class, 'index'])->name('settings.ads');
    Route::post('/settings/ads/update', [AdsController::class, 'update'])->name('settings.ads.update');

    // Blog Setting
    Route::get('/settings/blog', [BlogSettingController::class, 'index'])->name('settings.blog');
    Route::post('/settings/blog/update', [BlogSettingController::class, 'update'])->name('settings.blog.update');

    // languages
    Route::resource('/settings/languages', LanguageController::class);
    Route::post('/settings/languages/update_translation', [LanguageController::class, 'update_translation'])->name('languages.update_translation');
    Route::get('/settings/languages/{language}/seo', [LanguageController::class, 'show_seo'])->name('languages.show.seo');
    Route::get('/settings/languages/{language}/text', [LanguageController::class, 'text'])->name('languages.show.text');

    // SMTP Setting
    Route::get('/settings/smtp', [SmtpController::class, 'index'])->name('settings.smtp');
    Route::post('/settings/smtp/update', [SmtpController::class, 'update'])->name('settings.smtp.update');
    Route::post('/settings/check/smtp', [SmtpController::class, 'check'])->name('check.smtp');
    // Profile Settings
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::post('/profile/info/update', [ProfileController::class, 'changeInfo'])->name('settings.info.update');
    Route::post('/profile/password/update', [ProfileController::class, 'changePassword'])->name('settings.password.update');

    // API  Settings
    Route::get('/settings/api', [APIController::class, 'admin_api'])->name('settings.api');

    Route::get('/settings/css_js', [GeneralController::class, 'css_js'])->name('settings.css.js');
    Route::post('/settings/css_js/update', [GeneralController::class, 'css_js_update'])->name('settings.css.js.update');

    Route::get('/posts/checkslug', [PostController::class, 'checkSlug'])->name('posts.checkslug');
    Route::get('/categories/checkslug', [CategoryController::class, 'checkSlug'])->name('categories.checkslug');
    Route::get('/pages/checkslug', [PageController::class, 'checkSlug'])->name('pages.checkslug');
    Route::get('/posts/getcategory/{lang}', [PostController::class, 'getCategory'])->name('posts.getCategory');
    Route::post('ckeditor/image_upload', [PageController::class, 'upload'])->name('ckeditor.upload');

    Route::resource('/posts', PostController::class);
    Route::resource('/categories', CategoryController::class);
    Route::resource('/pages', PageController::class);
    Route::resource('/features', FeatureController::class);
    Route::resource('/menu', MenuController::class);

    Route::get('/clear-cache', [DashboardController::class, 'clear'])->name('clear.cache');
});

Auth::routes(['register' => false]);

Route::get('/delete', [TrashMailController::class, 'delete'])->name('delete');

Route::get('/delete/{id}', [TrashMailController::class, 'deletemessage'])->name('delete.message');

Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::post('/check_bot', [TrashMailController::class, 'check_bot'])->name('check_bot');

Route::post('/create', [TrashMailController::class, 'create'])->name('create');

Route::get('/download/{id}/{file?}', [TrashMailController::class, 'download']);

Route::post('/messages', [TrashMailController::class, 'messages'])->name('messages');

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeCookieRedirect', 'localizationRedirect', 'localeViewPath'],
], function () {
    if (ModelSettings::selectSettings('enable_blog')) {
        Route::get('/blog', [BlogController::class, 'index'])->name('blog');

        Route::get('/post/{slug}', [PostController::class, 'show'])->name('post');

        Route::get('/category/{slug}', [CategoryController::class, 'show'])->name('category');
    }

    Route::get('/', [TrashMailController::class, 'index'])->name('home');

    Route::get('/index', [TrashMailController::class, 'index'])->name('index');

    Route::get('/change', [TrashMailController::class, 'change'])->name('change');

    Route::get('/view/{id}', [TrashMailController::class, 'show'])->name('view');

    Route::get('/message/{id}', [TrashMailController::class, 'message'])->name('message');

    Route::get('/page/{slug}', [PageController::class, 'show'])->name('page');

    Route::get('/contact', [ContactController::class, 'index'])->name('contact');

    Route::get('/token/{token}', [TrashMailController::class, 'tokenToEmail']); // Only API
});

resources/views/backend/pages/create.blade.php
@extends('layouts.admin')

@section('content')
<section class="section">
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{route('pages.index')}}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>{{__('Create New Page')}}</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{route('dashboard')}}">{{__('Dashboard')}}</a></div>
            <div class="breadcrumb-item"><a href="{{route('pages.index')}}">{{__('Pages')}}</a></div>
            <div class="breadcrumb-item">{{__('Create New Page')}}</div>
        </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">{{__('Create New Page')}}</h2>
        <p class="section-lead">
            {{__('On this page you can create a new page and fill in all fields.')}}
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{__('Write Your Page')}}</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('pages.store')}}" method="POST" autocomplete="on"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Title')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('title') is-invalid @enderror"
                                        id="title" name="title" value="{{ old('title') }}" required placeholder="Titel">
                                    @error('title')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Slug')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('slug') is-invalid @enderror"
                                        id="slug" name="slug" value="{{ old('slug') }}" required placeholder="Slug">
                                    @error('slug')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Content')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <textarea id="content" name="content">{{ old('content') }}</textarea>
                                    <div class="mb-3">
                                        <input type="hidden"
                                            class="form-control @error('content') is-invalid @enderror">
                                        @error('content')
                                        <div class="invalid-feedback">
                                            <strong>{{ $message }}</strong>
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Language')}}
                                    :</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control selectric" name="lang">
                                        @foreach ($languages as $language)
                                        <option value="{{ $language->code }}">{{ $language->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('lang')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Status')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control selectric" name="status">
                                        <option value="1">{{__('Publish')}}</option>
                                        <option value="0">{{__('Draft')}}</option>
                                    </select>
                                </div>
                            </div>

                            <hr>

                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Meta Title
                                    (Optional)')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('mete_title') is-invalid @enderror"
                                        name="mete_title" value="{{ old('mete_title') }}"
                                        placeholder="Page Title - Your Site">
                                    @error('mete_title')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Meta
                                    Description (Optional Max:160)')}}
                                </label>
                                <div class="col-sm-12 col-md-7">
                                    <textarea class="form-control @error('meta_description') is-invalid @enderror"
                                        name="meta_description" placeholder="Description"></textarea>
                                    @error('meta_description')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary">{{__('Create Page')}}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('styles')
<link href="{{ asset('assets/css/selectric.css') }}" rel="stylesheet">
@endpush

@push('libraies')
<script src="{{ asset('assets/js/vendor/jquery.selectric.min.js') }}"></script>
<script src="{{ asset('assets/js/ckeditor/ckeditor.js') }}"></script>
@endpush

@push('scripts')
<!--SET DYNAMIC VARIABLE IN SCRIPT -->
<script type="text/javascript">
    var checkslug_title = "{{route('pages.checkslug')}}";
  CKEDITOR.replace('content', {
      filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
      filebrowserUploadMethod: 'form'
  });

</script>
@endpush

resources/views/backend/pages/edit.blade.php
@extends('layouts.admin')

@section('content')
<section class="section">
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{route('pages.index')}}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>{{__('Edit Page')}}</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{route('dashboard')}}">{{__('Dashboard')}}</a></div>
            <div class="breadcrumb-item"><a href="{{route('pages.index')}}">{{__('Pages')}}</a></div>
            <div class="breadcrumb-item">{{__('Edit Page')}}</div>
        </div>
    </div>

    <div class="section-body">
        <h2 class="section-title">{{__('Edit Page')}}</h2>
        <p class="section-lead">
            {{__('On this page you can edit page and fill in all fields.')}}
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{__('Edit Your Page')}}</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('pages.update' , $page->id) }}" method="POST" autocomplete="on"
                            enctype="multipart/form-data">
                            @csrf
                            @method("PUT")
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Title')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('title') is-invalid @enderror"
                                        id="title" name="title" value="{{ $page->title }}" required placeholder="Titel">
                                    @error('title')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Slug')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('slug') is-invalid @enderror"
                                        id="slug" name="slug" value="{{ $page->slug }}" required placeholder="Slug">
                                    @error('slug')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Content')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <textarea id="summernote" name="content">{{ $page->content }}</textarea>
                                    <div class="mb-3">
                                        <input type="hidden"
                                            class="form-control @error('content') is-invalid @enderror">
                                        @error('content')
                                        <div class="invalid-feedback">
                                            <strong>{{ $message }}</strong>
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Language')}}
                                    :</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control selectric" name="lang">
                                        @foreach ($languages as $language)
                                        <option value="{{ $language->code}}" @if($page->lang == $language->code)
                                            selected @endif>{{ $language->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('lang')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Status')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control selectric" name="status">
                                        <option value="1" {{ $page->status == 1 ? 'selected' : '' }}>{{__('Publish')}}
                                        </option>
                                        <option value="0" {{ $page->status == 0 ? 'selected' : '' }}>{{__('Draft')}}
                                        </option>
                                    </select>
                                </div>
                            </div>


                            <hr>

                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Meta Title
                                    (Optional)')}}</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('mete_title') is-invalid @enderror"
                                        name="mete_title" value="{{ $page->mete_title }}"
                                        placeholder="Page Title - Your Site">
                                    @error('mete_title')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Meta
                                    Description (Optional Max:160)')}}
                                </label>
                                <div class="col-sm-12 col-md-7">
                                    <textarea class="form-control @error('meta_description') is-invalid @enderror"
                                        name="meta_description"
                                        placeholder="Description">{{ $page->meta_description }}</textarea>
                                    @error('meta_description')
                                    <div class="invalid-feedback">
                                        <strong>{{ $message }}</strong>
                                    </div>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary">{{__('Update')}}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('styles')
<link href="{{ asset('assets/css/selectric.css') }}" rel="stylesheet">
@endpush

@push('libraies')
<script src="{{ asset('assets/js/vendor/jquery.selectric.min.js') }}"></script>
<script src="{{ asset('assets/js/ckeditor/ckeditor.js') }}"></script>
@endpush

@push('scripts')
<!--SET DYNAMIC VARIABLE IN SCRIPT -->
<script type="text/javascript">
    CKEDITOR.replace('content', {
      filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
      filebrowserUploadMethod: 'form'
  });

</script>
@endpush

resources/views/backend/pages/index.blade.php
@extends('layouts.admin')

@section('content')
<section class="section">
  <div class="section-header">
    <h1>{{__('Pages')}}</h1>
    <div class="section-header-button">
      <a href="{{route("pages.create")}}" class="btn btn-primary">{{__('Add New')}}</a>
    </div>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{route("dashboard")}}">{{__('Dashboard')}}</a></div>
      <div class="breadcrumb-item">{{__('Pages')}}</div>
    </div>
  </div>
  <div class="section-body">
    <h2 class="section-title">{{__('Pages')}}</h2>
    <p class="section-lead">
      {{__('You can manage all pages, such as editing, deleting and more.')}}
    </p>
    <div class="row mt-4">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>{{__('All Pages')}}</h4>
          </div>
          <div class="card-body">
            <div class="clearfix mb-3"></div>
            <div class="table-responsive">
              <table class="table table-striped" id="table-1">
                <thead>
                  <tr>
                    <th class="text-center">#</th>
                    <th>{{__('Title')}}</th>
                    <th>{{__('Created At')}}</th>
                    <th>{{__('Language')}}</th>
                    <th>{{__('Status')}}</th>
                    <th>{{__('Action')}}</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($pages as $page)
                  <tr>
                    <td>{{$page->id}}</td>
                    <td>{{$page->title}}
                    </td>
                    <td>
                      {{ToDate($page->created_at)}}
                    </td>
                    <td>{{$page->lang}}</td>
                    <td>
                      @if ($page->status == 1)
                      <span class='badge badge-primary'>{{__('Published')}}</span>
                      @else
                      <span class='badge badge-warning'>{{__('Draft')}}</span>
                      @endif
                    </td>
                    <td class="text-center">
                      <a href="{{route('pages.edit' ,$page->id )}}" class="btn btn-primary bg_primary btn-sm"><i
                          class="fa fa-edit"></i></a>
                      <button class="btn btn-danger bg_danger btn-sm confirm" id="{{$page->id}}">
                        <i class="fa fa-trash"></i>
                      </button>
                      <form id="delete{{$page->id}}" action="{{route('pages.destroy' ,$page->id ) }}" method="POST"
                        class="d-none">
                        @csrf
                        @method("DELETE")
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

@push('styles')
<link href="{{ asset('assets/css/selectric.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/select.bootstrap4.min.css') }}" rel="stylesheet">
@endpush


@push('libraies')
<script src="{{ asset('assets/js/vendor/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/select.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/jquery.selectric.min.js') }}"></script>
@endpush