routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\APIController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PostController;
use App\Models\Settings as ModelSettings;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TrashMailController;
use App\Http\Controllers\Settings\AdsController;
use App\Http\Controllers\Settings\SeoController;
use App\Http\Controllers\Settings\SmtpController;
use App\Http\Controllers\Settings\GeneralController;
use App\Http\Controllers\Settings\ProfileController;
use App\Http\Controllers\Settings\BlogSettingController;

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('/update', [DashboardController::class, 'update'])->name('update');

    Route::get('/', function () {
        return to_route('dashboard');
    })->name('admin');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/settings', [DashboardController::class, 'settings'])->name('settings');

    // General Settings
    Route::get('/settings/general', [GeneralController::class, 'index'])->name('settings.general');
    Route::post('/settings/general/update', [GeneralController::class, 'update'])->name('settings.general.update');
    Route::post('/settings/general/update2', [GeneralController::class, 'update2'])->name('settings.general.update2');
    Route::post('/settings/check/imap', [GeneralController::class, 'check_imap'])->name('check.imap');

    // Seo Settings
    Route::get('/settings/seo', [SeoController::class, 'index'])->name('settings.seo');
    Route::post('/settings/seo/update', [SeoController::class, 'update'])->name('settings.seo.update');

    Route::get('/settings/license', [GeneralController::class, 'license'])->name('settings.license');
    Route::post('/settings/license/update', [GeneralController::class, 'license_update'])->name('settings.license.update');

    // Ads Settings
    Route::get('/settings/ads', [AdsController::class, 'index'])->name('settings.ads');
    Route::post('/settings/ads/update', [AdsController::class, 'update'])->name('settings.ads.update');

    // Blog Setting
    Route::get('/settings/blog', [BlogSettingController::class, 'index'])->name('settings.blog');
    Route::post('/settings/blog/update', [BlogSettingController::class, 'update'])->name('settings.blog.update');

    // languages
    Route::resource('/settings/languages', LanguageController::class);
    Route::post('/settings/languages/update_translation', [LanguageController::class, 'update_translation'])->name('languages.update_translation');
    Route::get('/settings/languages/{language}/seo', [LanguageController::class, 'show_seo'])->name('languages.show.seo');
    Route::get('/settings/languages/{language}/text', [LanguageController::class, 'text'])->name('languages.show.text');

    // SMTP Setting
    Route::get('/settings/smtp', [SmtpController::class, 'index'])->name('settings.smtp');
    Route::post('/settings/smtp/update', [SmtpController::class, 'update'])->name('settings.smtp.update');
    Route::post('/settings/check/smtp', [SmtpController::class, 'check'])->name('check.smtp');
    // Profile Settings
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::post('/profile/info/update', [ProfileController::class, 'changeInfo'])->name('settings.info.update');
    Route::post('/profile/password/update', [ProfileController::class, 'changePassword'])->name('settings.password.update');

    // API  Settings
    Route::get('/settings/api', [APIController::class, 'admin_api'])->name('settings.api');

    Route::get('/settings/css_js', [GeneralController::class, 'css_js'])->name('settings.css.js');
    Route::post('/settings/css_js/update', [GeneralController::class, 'css_js_update'])->name('settings.css.js.update');

    Route::get('/posts/checkslug', [PostController::class, 'checkSlug'])->name('posts.checkslug');
    Route::get('/categories/checkslug', [CategoryController::class, 'checkSlug'])->name('categories.checkslug');
    Route::get('/pages/checkslug', [PageController::class, 'checkSlug'])->name('pages.checkslug');
    Route::get('/posts/getcategory/{lang}', [PostController::class, 'getCategory'])->name('posts.getCategory');
    Route::post('ckeditor/image_upload', [PageController::class, 'upload'])->name('ckeditor.upload');

    Route::resource('/posts', PostController::class);
    Route::resource('/categories', CategoryController::class);
    Route::resource('/pages', PageController::class);
    Route::resource('/features', FeatureController::class);
    Route::resource('/menu', MenuController::class);

    Route::get('/clear-cache', [DashboardController::class, 'clear'])->name('clear.cache');
});

Auth::routes(['register' => false]);

Route::get('/delete', [TrashMailController::class, 'delete'])->name('delete');

Route::get('/delete/{id}', [TrashMailController::class, 'deletemessage'])->name('delete.message');

Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::post('/check_bot', [TrashMailController::class, 'check_bot'])->name('check_bot');

Route::post('/create', [TrashMailController::class, 'create'])->name('create');

Route::get('/download/{id}/{file?}', [TrashMailController::class, 'download']);

Route::post('/messages', [TrashMailController::class, 'messages'])->name('messages');

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeCookieRedirect', 'localizationRedirect', 'localeViewPath'],
], function () {
    if (ModelSettings::selectSettings('enable_blog')) {
        Route::get('/blog', [BlogController::class, 'index'])->name('blog');

        Route::get('/post/{slug}', [PostController::class, 'show'])->name('post');

        Route::get('/category/{slug}', [CategoryController::class, 'show'])->name('category');
    }

    Route::get('/', [TrashMailController::class, 'index'])->name('home');

    Route::get('/index', [TrashMailController::class, 'index'])->name('index');

    Route::get('/change', [TrashMailController::class, 'change'])->name('change');

    Route::get('/view/{id}', [TrashMailController::class, 'show'])->name('view');

    Route::get('/message/{id}', [TrashMailController::class, 'message'])->name('message');

    Route::get('/page/{slug}', [PageController::class, 'show'])->name('page');

    Route::get('/contact', [ContactController::class, 'index'])->name('contact');

    Route::get('/token/{token}', [TrashMailController::class, 'tokenToEmail']); // Only API
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{$setdata['name']}}</title>
    <link rel="icon" type="image/png" href="{{asset($setdata['favicon'])}}" />

    <!-- General CSS Files -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/font-awesome.css') }}" rel="stylesheet">

    <!-- CSS Libraries -->
    @stack('styles')

    <!-- Template CSS -->
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/components.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/custom.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <div class="main-wrapper">
            <div class="navbar-bg"></div>

            @include('layouts.header')

            @include('layouts.sidebar')

            <!-- Main Content -->
            <div class="main-content">
                @yield('content')
            </div>
            <footer class="main-footer">
                <div class="footer-left">
                    {{ __('Copyright')}} &copy; {{date('Y')}} <div class="bullet"></div> {{ __('Powered By')}}
                    <a href="{{$setdata['site_url']}}">{{Str::of($setdata['name'])->limit(16)}}</a>
                </div>
                <div class="footer-right">
                    1.4v
                </div>
            </footer>
        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="{{ asset('assets/js/vendor/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor/index.umd.js') }}"></script>
    <script src="{{ asset('assets/js/vendor/popper.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor/jquery.nicescroll.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor/moment.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor/sweetalert2.js') }}"></script>

    <!-- JS Libraies -->
    @stack('libraies')

    <!-- Template JS File -->
    <script src="{{ asset('assets/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/js/custom.js') }}"></script>

    @stack('scripts')
    @if (session()->has('success'))
    <!--SET DYNAMIC VARIABLE IN SCRIPT -->
    <script type="text/javascript">
        var alert = '{{session()->get('success')}}';
      var icon  = 'success';
    </script>
    <script src="{{ asset('assets/js/vendor/alert.js') }}"></script>
    @endif
    @if (session()->has('demo'))
    <!--SET DYNAMIC VARIABLE IN SCRIPT -->
    <script type="text/javascript">
        var alert = '{{session()->get('demo')}}';
      var icon  = 'error';
    </script>
    <script src="{{ asset('assets/js/vendor/alert.js') }}"></script>
    @endif
    @if (session()->has('error'))
    <!--SET DYNAMIC VARIABLE IN SCRIPT -->
    <script type="text/javascript">
        var alert = '{{session()->get('error')}}';
    var icon  = 'error';
    </script>
    <script src="{{ asset('assets/js/vendor/alert.js') }}"></script>
    @endif

    <script type="text/javascript">
        "use strict";
            const BASE_URL = "{{ url('/admin') }}";
    </script>

</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>@yield('title')</title>

  <!-- General CSS Files -->

  <link rel="icon" type="image/png" href="{{asset($setdata['favicon'])}}" />
  <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/css/font-awesome.css') }}" rel="stylesheet">

  <!-- CSS Libraries -->
  @stack('styles')

  <!-- Template CSS -->
  <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
  <link href="{{ asset('assets/css/components.css') }}" rel="stylesheet">
</head>

<body>
  <div id="app">
    <section class="section">
      @yield('content')
    </section>
  </div>

  <!-- General JS Scripts -->
  <script src="{{ asset('assets/js/vendor/jquery.min.js') }}"></script>
  <script src="{{ asset('assets/js/vendor/popper.min.js') }}"></script>
  <script src="{{ asset('assets/js/vendor/bootstrap.min.js') }}"></script>
  <script src="{{ asset('assets/js/vendor/jquery.nicescroll.min.js') }}"></script>
  <script src="{{ asset('assets/js/vendor/moment.min.js') }}"></script>

  <!-- JS Libraies -->
  @stack('libraies')

  <!-- Template JS File -->
  <script src="{{ asset('assets/js/scripts.js') }}"></script>
  <script src="{{ asset('assets/js/custom.js') }}"></script>

  @stack('scripts')


</body>

</html>

resources/views/layouts/errors.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@yield('title')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- font awesome icons -->
    <link href="{{ asset('assets/css/font-awesome.css') }}" rel="stylesheet">
    <!-- bootstrap css -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- main css -->
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">


    <link rel="icon" type="image/png" href="{{asset($setdata['favicon'])}}" />
    <!--SET DYNAMIC VARIABLE IN STYLE-->
    <style>
        :root {
          --main-color: {{$setdata['main_color']}};
          --color1: {{$setdata['secondary_color']}};
        }
      </style>

</head>

<body class="error_page">
    <div class="full-screen-size-fixed-container d-flex justify-content-center align-items-center">
        <div class="p-3 text-center">
            <h1 class="display-1 font-weight-bold ">@yield('code')</h1>
            <h4 class="text-muted">@yield('message')</h4>
            <p class="mb-4">@yield('message2')</p>
            <a class="btn-2" href="{{url('/')}}" role="button"><i
                    class="fas fa-house-user mr-2"></i>{{translate('Back to Home')}}</a>
        </div>

    </div>

</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <ul class="navbar-nav mr-3 mr-auto">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="{{route('home')}}" target="_blank" class="btn btn-dark">{{__('Go to website')}}</a></li>
    </ul>
    <ul class="navbar-nav navbar-right ml-auto">
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{asset(auth()->user()->avater)}}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{__('Hi')}}, {{auth()->user()->name}} </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{route('profile')}}" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> {{__('Profile')}}
                </a>
                <div class="dropdown-divider"></div>
                <form method="POST" action="{{ route('logout') }}">
                    @csrf
                    <button class="dropdown-item has-icon text-danger" type="submit"> {{__('Logout')}}</button>
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/setting.blade.php
<div class="col-md-4">
    <div class="card">
        <div class="card-header">
            <h4>{{__('Jump To')}}</h4>
        </div>
        <div class="card-body">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item"><a href="{{route('settings.general')}}"
                        class="nav-link {{ Request()->segment(3) == "general" ? "active" : '' }}">{{__('General Settings')}}</a></li>
                <li class="nav-item"><a href="{{route('settings.seo')}}" class="nav-link {{ Request()->segment(3) == "seo" ? "active" : '' }}">{{__('SEO')}}</a></li>
                <li class="nav-item"><a href="{{route('settings.ads')}}" class="nav-link {{ Request()->segment(3) == "ads" ? "active" : '' }}">{{__('Ads')}}</a></li>
                <li class="nav-item"><a href="{{route('settings.blog')}}" class="nav-link {{ Request()->segment(3) == "blog" ? "active" : '' }}">{{__('Blog Settings')}}</a></li>
                <li class="nav-item"><a href="{{route('settings.smtp')}}" class="nav-link {{ Request()->segment(3) == "smtp" ? "active" : '' }}">{{__('SMTP')}}</a></li>
                <li class="nav-item"><a href="{{route('languages.index')}}"
                        class="nav-link {{ Request()->segment(3) == "languages" ? "active" : ''
                        }}">{{__('Languages')}}</a></li>
                <li class="nav-item"><a href="{{route('settings.api')}}" class="nav-link {{ Request()->segment(3) == "api" ? "active" : '' }}">{{__('API')}}</a></li>
                <li class="nav-item"><a href="{{route('settings.css.js')}}"
                        class="nav-link {{ Request()->segment(3) == "css_js" ? "active" : '' }}">{{__('Custom CSS &
                        JS')}}</a></li>

            </ul>
        </div>
    </div>
</div>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{route('admin')}}">{{Str::of($setdata['name'])->limit(16)}}</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{route('admin')}}">{{ Str::of($setdata['name'])->limit(2, '') }}</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">{{request()->segment(2)}}</li>

            <li {{request()->segment(2) == "dashboard" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('dashboard') }}">
                    <i class="fas fa-fire"></i> <span>{{__('Dashboard')}}</span>
                </a>
            </li>

            <li {{request()->segment(2) == "categories" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('categories.index') }}">
                    <i class="fas fa-pencil-ruler"></i><span>{{__('Categories')}}</span>
                </a>
            </li>

            <li {{request()->segment(2) == "posts" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('posts.index') }}">
                    <i class="fas fa-newspaper"></i> <span>{{__('Posts')}}</span>
                </a>
            </li>

            <li {{request()->segment(2) == "pages" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('pages.index') }}">
                    <i class="fas fa-file-alt"></i><span>{{__('Pages')}}</span>
                </a>
            </li>

            <li {{request()->segment(2) == "features" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('features.index') }}">
                    <i class="fas fa-paint-brush"></i><span>{{__('Features')}}</span>
                </a>
            </li>

            <li {{request()->segment(2) == "menu" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('menu.index') }}">
                    <i class="fas fa-grip-horizontal"></i><span>{{__('Simple Menu')}}</span>
                </a>
            </li>


            <li {{request()->segment(2) == "settings" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('settings') }}">
                    <i class="fas fa-cog"></i> <span>{{__('Settings')}}</span>
                </a>
            </li>

            <li {{request()->segment(2) == "css&js" ? 'class=active' : ""}}>
                <a class="nav-link" href="{{ route('settings.css.js') }}">
                    <i class="fas fa-cog"></i> <span>{{__('Custom CSS & JS')}}</span>
                </a>
            </li>

            <li>
                <a class="nav-link" href="{{ route('clear.cache') }}">
                    <i class="fas fa-hand-sparkles"></i><span>{{__('Clear Cache')}}</span>
                </a>
            </li>


        </ul>
    </aside>
</div>