routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\APIController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PostController;
use App\Models\Settings as ModelSettings;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FeatureController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TrashMailController;
use App\Http\Controllers\Settings\AdsController;
use App\Http\Controllers\Settings\SeoController;
use App\Http\Controllers\Settings\SmtpController;
use App\Http\Controllers\Settings\GeneralController;
use App\Http\Controllers\Settings\ProfileController;
use App\Http\Controllers\Settings\BlogSettingController;

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('/update', [DashboardController::class, 'update'])->name('update');

    Route::get('/', function () {
        return to_route('dashboard');
    })->name('admin');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/settings', [DashboardController::class, 'settings'])->name('settings');

    // General Settings
    Route::get('/settings/general', [GeneralController::class, 'index'])->name('settings.general');
    Route::post('/settings/general/update', [GeneralController::class, 'update'])->name('settings.general.update');
    Route::post('/settings/general/update2', [GeneralController::class, 'update2'])->name('settings.general.update2');
    Route::post('/settings/check/imap', [GeneralController::class, 'check_imap'])->name('check.imap');

    // Seo Settings
    Route::get('/settings/seo', [SeoController::class, 'index'])->name('settings.seo');
    Route::post('/settings/seo/update', [SeoController::class, 'update'])->name('settings.seo.update');

    Route::get('/settings/license', [GeneralController::class, 'license'])->name('settings.license');
    Route::post('/settings/license/update', [GeneralController::class, 'license_update'])->name('settings.license.update');

    // Ads Settings
    Route::get('/settings/ads', [AdsController::class, 'index'])->name('settings.ads');
    Route::post('/settings/ads/update', [AdsController::class, 'update'])->name('settings.ads.update');

    // Blog Setting
    Route::get('/settings/blog', [BlogSettingController::class, 'index'])->name('settings.blog');
    Route::post('/settings/blog/update', [BlogSettingController::class, 'update'])->name('settings.blog.update');

    // languages
    Route::resource('/settings/languages', LanguageController::class);
    Route::post('/settings/languages/update_translation', [LanguageController::class, 'update_translation'])->name('languages.update_translation');
    Route::get('/settings/languages/{language}/seo', [LanguageController::class, 'show_seo'])->name('languages.show.seo');
    Route::get('/settings/languages/{language}/text', [LanguageController::class, 'text'])->name('languages.show.text');

    // SMTP Setting
    Route::get('/settings/smtp', [SmtpController::class, 'index'])->name('settings.smtp');
    Route::post('/settings/smtp/update', [SmtpController::class, 'update'])->name('settings.smtp.update');
    Route::post('/settings/check/smtp', [SmtpController::class, 'check'])->name('check.smtp');
    // Profile Settings
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::post('/profile/info/update', [ProfileController::class, 'changeInfo'])->name('settings.info.update');
    Route::post('/profile/password/update', [ProfileController::class, 'changePassword'])->name('settings.password.update');

    // API  Settings
    Route::get('/settings/api', [APIController::class, 'admin_api'])->name('settings.api');

    Route::get('/settings/css_js', [GeneralController::class, 'css_js'])->name('settings.css.js');
    Route::post('/settings/css_js/update', [GeneralController::class, 'css_js_update'])->name('settings.css.js.update');

    Route::get('/posts/checkslug', [PostController::class, 'checkSlug'])->name('posts.checkslug');
    Route::get('/categories/checkslug', [CategoryController::class, 'checkSlug'])->name('categories.checkslug');
    Route::get('/pages/checkslug', [PageController::class, 'checkSlug'])->name('pages.checkslug');
    Route::get('/posts/getcategory/{lang}', [PostController::class, 'getCategory'])->name('posts.getCategory');
    Route::post('ckeditor/image_upload', [PageController::class, 'upload'])->name('ckeditor.upload');

    Route::resource('/posts', PostController::class);
    Route::resource('/categories', CategoryController::class);
    Route::resource('/pages', PageController::class);
    Route::resource('/features', FeatureController::class);
    Route::resource('/menu', MenuController::class);

    Route::get('/clear-cache', [DashboardController::class, 'clear'])->name('clear.cache');
});

Auth::routes(['register' => false]);

Route::get('/delete', [TrashMailController::class, 'delete'])->name('delete');

Route::get('/delete/{id}', [TrashMailController::class, 'deletemessage'])->name('delete.message');

Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::post('/check_bot', [TrashMailController::class, 'check_bot'])->name('check_bot');

Route::post('/create', [TrashMailController::class, 'create'])->name('create');

Route::get('/download/{id}/{file?}', [TrashMailController::class, 'download']);

Route::post('/messages', [TrashMailController::class, 'messages'])->name('messages');

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeCookieRedirect', 'localizationRedirect', 'localeViewPath'],
], function () {
    if (ModelSettings::selectSettings('enable_blog')) {
        Route::get('/blog', [BlogController::class, 'index'])->name('blog');

        Route::get('/post/{slug}', [PostController::class, 'show'])->name('post');

        Route::get('/category/{slug}', [CategoryController::class, 'show'])->name('category');
    }

    Route::get('/', [TrashMailController::class, 'index'])->name('home');

    Route::get('/index', [TrashMailController::class, 'index'])->name('index');

    Route::get('/change', [TrashMailController::class, 'change'])->name('change');

    Route::get('/view/{id}', [TrashMailController::class, 'show'])->name('view');

    Route::get('/message/{id}', [TrashMailController::class, 'message'])->name('message');

    Route::get('/page/{slug}', [PageController::class, 'show'])->name('page');

    Route::get('/contact', [ContactController::class, 'index'])->name('contact');

    Route::get('/token/{token}', [TrashMailController::class, 'tokenToEmail']); // Only API
});

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Language;
use App\Models\Settings;
use App\Models\Translate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use voku\helper\AntiXSS;

class LanguageController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): \Illuminate\Contracts\View\View
    {
        $lang = Language::pluck('code')->toarray();

        return view('backend.settings.languages.index')->with('languages', Language::all())->with('lang', $lang);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): void
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate the Language fields
        $request->validate([
            'name' => 'required|max:255',
            'code' => 'required|max:10|unique:languages',
            'rtl' => 'boolean',
        ]);

        if ($request->input('rtl') == null) {
            $request->rtl = 0;
        }

        $language = new Language();
        $language->name = $request->input('name');
        $language->code = $request->input('code');
        $language->rtl = $request->input('rtl');

        $language->save();

        $translates = Translate::where('lang', Settings::selectSettings('lang'))->get();

        foreach ($translates as $translate) {
            $new_translate = new Translate();
            $new_translate->lang = $request->input('code');
            $new_translate->key = $translate->key;
            $new_translate->collection = $translate->collection;
            $new_translate->value = '';
            $new_translate->save();
        }

        $request->session()->flash('success', 'Language Created Successfuly');

        return redirect(route('languages.index'));
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Language $language)
    {
        $translates = Translate::where('lang', $language->code)->where('collection', 'general')->get();

        return view('backend.settings.languages.show', [
            'language' => $language,
            'translates' => $translates,
        ],[
            'language' => $language,
            'translates' => $translates,
        ]);
    }

    public function show_seo(Language $language)
    {
        $translates = Translate::where('lang', $language->code)->where('collection', 'seo')->get();

        return view('backend.settings.languages.show', [
            'language' => $language,
            'translates' => $translates,
        ]);
    }

    public function text(Language $language)
    {
        $translates = Translate::where('lang', $language->code)->where('collection', 'text')->get();

        return view('backend.settings.languages.show', [
            'language' => $language,
            'translates' => $translates,
        ],[
            'language' => $language,
            'translates' => $translates,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Language $language): \Illuminate\Contracts\View\View
    {
        $lang = Language::pluck('code')->toarray();

        if (($key = array_search($language->code, $lang)) !== false) {
            unset($lang[$key]);
        }

        return view('backend.settings.languages.edit')->with('language', $language)->with('lang', $lang);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Models\Language  $language
     */
    public function update_translation(Request $request): \Illuminate\Http\RedirectResponse
    {
        foreach ($request->input('values') as $id => $value) {
            $translation = Translate::where('id', '=', $id)->first();
            if ($translation != null) {
                //dd($value);

                //$antiXss = new AntiXSS();

                //$value_check = strip_tags($value, '<b><u><i><a><span><h1><h2><h3><h4><h5><h6><br>');

                //$value__after_check = $antiXss->xss_clean($value_check);

                $translation->value = $value;
                $translation->save();
            }
        }

        $request->session()->flash('success', 'Updated Successfuly');

        return redirect()->back();
    }

    public function update(Request $request, Language $language)
    {
        if (Settings::selectSettings('lang') == $language->code) {
            $request->session()->flash('error', 'Default language can not be edited');

            return redirect(route('languages.index'));
        }

        //validate the Language fields
        $request->validate([
            'name' => 'required|max:255',
            'code' => 'required|max:10',
            'rtl' => 'boolean',
        ]);

        if ($request->input('rtl') == null) {
            $request->rtl = 0;
        }

        $old_lang = $language->code;

        $language->update([
            'name' => $request->input('name'),
            'code' => $request->input('code'),
            'rtl' => $request->input('rtl'),
        ]);

        $translates = Translate::where('lang', $old_lang)->get();

        foreach ($translates as $translate) {
            $translate->update([
                'lang' => $request->input('code'),
            ]);
        }

        $request->session()->flash('success', 'Language Created Successfuly');

        return redirect(route('languages.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Language $language)
    {
        if (Settings::selectSettings('lang') == $language->code) {
            $request->session()->flash('error', 'Default language can not be deleted');

            return redirect(route('languages.index'));
        }

        $old_lang = $language->code;

        $language->delete();

        $translates = Translate::where('lang', $old_lang)->get();

        foreach ($translates as $translate) {
            $translate->delete();
        }

        $request->session()->flash('success', 'Language Deleted Successfuly');

        return redirect(route('languages.index'));
    }

    public function switchLang($lang): \Illuminate\Http\RedirectResponse
    {
        $language = Language::pluck('code')->toarray();

        if (in_array($lang, $language)) {
            Cookie::queue('locale', $lang, 365 * 1440);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/settings/AdsController.php
<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use App\Models\Settings;
use Illuminate\Http\Request;

class AdsController extends Controller
{
    public function index(): \Illuminate\Contracts\View\View
    {
        $settings = Settings::whereIn('key', ['top_ad', 'bottom_ad', 'right_ad', 'left_ad', 'head_ad', 'sidebar_ad'])->get();
        $setting = $settings->pluck('value', 'key')->all();

        return view('backend.settings.ads')->with('setting', $setting);
    }

    public function update(Request $request)
    {
        $settings = Settings::whereIn('key', ['top_ad', 'bottom_ad', 'right_ad', 'left_ad', 'head_ad', 'sidebar_ad'])->get();
        foreach ($settings as $setting) {
            $key = $setting->key;
            $setting->value = $request->$key;
            $setting->save();
        }

        $request->session()->flash('success', 'Updated Successfuly');

        return redirect()->route('settings.ads');
    }
}

app/Http/Controllers/settings/BlogSettingController.php
<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use App\Models\Settings;
use Illuminate\Http\Request;

class BlogSettingController extends Controller
{
    public function index(): \Illuminate\Contracts\View\View
    {
        $settings = Settings::whereIn('key', ['enable_blog', 'popular_posts', 'max_posts', 'disqus'])->get();
        $setting = $settings->pluck('value', 'key')->all();

        return view('backend.settings.blog')->with('setting', $setting);
    }

    public function update(Request $request)
    {
        $request->validate([
            'enable_blog' => 'boolean',
            'popular_posts_in_page' => 'numeric|min:3',
            'max_posts' => 'numeric|min:2',

        ]);

        if ($request->enable_blog == null) {
            $request->enable_blog = 0;
        }

        $settings = Settings::whereIn('key', ['enable_blog', 'popular_posts', 'max_posts', 'disqus'])->get();
        foreach ($settings as $setting) {
            $key = $setting->key;
            $setting->value = $request->$key;
            $setting->save();
        }

        $request->session()->flash('success', 'Updated Successfuly');

        return redirect()->route('settings.blog');
    }
}

app/Http/Controllers/settings/ProfileController.php
<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();

        return view('backend.settings.profile', ['user' => $user]);
    }

    public function changeInfo(Request $request): \Illuminate\Http\RedirectResponse
    {
        $user = $request->user();

        $request->validate([
            'photo' => 'mimes:jpeg,png,jpg|max:2048',
            'name' => 'required|string|min:4',
            'email' => 'required|unique:users,email,'.$user->id,
        ]);

        if ($request->has('photo')) {
            $file = $request->photo;
            $user->avater = FileUpload($file, 'uploads/', $user->avater);
        }

        $user->update([
            $user->name = $request->name,
            $user->email = $request->email,
            $user->avater = $user->avater,
        ]);

        return redirect()->back()->with('success', 'Profile successfully changed!');
    }

    public function changePassword(Request $request): \Illuminate\Http\RedirectResponse
    {
        $request->validate([
            'current_password' => 'required',
            'password' => 'required|string|min:6|confirmed',
            'password_confirmation' => 'required',
        ]);

        $user = $request->user();

        if (! Hash::check($request->current_password, $user->password)) {
            return redirect()->back()->with('error', 'Current password does not match!');
        }

        $user->password = Hash::make($request->password);
        $user->save();

        return redirect()->back()->with('success', 'Password successfully changed!');
    }
}

resources/views/backend/settings/languages/edit.blade.php
@extends('layouts.admin')

@section('content')
<section class="section">
<div class="section-header">
    <div class="section-header-back">
        <a href="{{ route('languages.index')}}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>{{__('Edit Language')}}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard')}}">{{__('Dashboard')}}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('languages.index')}}">{{__('Languages')}}</a></div>
        <div class="breadcrumb-item">{{__('Edit Language')}}</div>
    </div>
</div>

<div class="section-body">
    <h2 class="section-title">{{__('Edit Language')}}</h2>
    <p class="section-lead">
        {{__('On this page you can edir language and fill in all fields.')}}
    </p>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>{{__('Edit Language')}}</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('languages.update' , $language->id) }}" method="POST">
                        @csrf
                        @method("PUT")
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Name') }} :</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" class="form-control @error('name') is-invalid @enderror"
                                    name="name" value="{{ $language->name }}" required placeholder='Name'>
                                @error('name')
                                <div class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('Title')}} :</label>
                            <div class="col-sm-12 col-md-7">
                                <select class="selectpicker  @error('code') is-invalid @enderror" required name="code"
                                data-live-search="true" data-width="100%">
                                @foreach(\File::files('assets/flags') as $path)
                                @if(!in_array(pathinfo($path)['filename'],$lang))
                                <option @if($language->code == pathinfo($path)['filename']) selected @endif value="{{ pathinfo($path)['filename'] }}" data-content="<div class=''><img src='{{ asset('assets/flags/'.pathinfo($path)['filename'].'.png') }}' 
                                    class='mr-2 flag_img'><span>{{ pathinfo($path)['filename'] }}</span></div>"></option>
                                @endif
                                @endforeach
                                </select>
                                @error('title')
                                <div class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{__('RTL')}} :</label>
                            <div class="col-sm-12 col-md-7">
                                <label class="custom-switch">
                                    <input type="checkbox" name="rtl" class="custom-switch-input" value="1"
                                        @if($language->rtl) checked @endif>
                                    <span class="custom-switch-indicator"></span>
                                    </label>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button class="btn btn-primary">{{__('Update')}}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/bootstrap-select.min.css') }}">
@endpush


@push('libraies')
<script src="{{ asset('assets/js/vendor/bootstrap-select.min.js') }}"></script>
@endpush

resources/views/backend/settings/languages/index.blade.php
@extends('layouts.admin')

@section('content')
<section class="section">
  <div class="section-header">
    <h1>{{__('Languages')}}</h1>
    <div class="section-header-button">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#LanguageModal">
        {{__('Add New')}}
      </button>
    </div>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{route("dashboard")}}">{{__('Dashboard')}}</a></div>
      <div class="breadcrumb-item">{{__('Languages')}}</div>
    </div>
  </div>
  <div class="section-body">
    <h2 class="section-title">{{__('Languages')}}</h2>
    <p class="section-lead">
      {{__('You can manage all languages, such as deleting and more.')}}
    </p>
    <div class="row mt-4">
      <div class="col-12">
        @if(Session::has('error'))
          <div class="alert alert-danger">
              {{ Session::get('error') }}
          </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4>{{__('All Languages')}}</h4>
          </div>
          <div class="card-body">
            <div class="clearfix mb-3"></div>
            <div class="table-responsive">
              <table class="table table-striped" id="table-1">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>{{__('Name')}}</th>
                    <th>{{__('Language Code')}}</th>
                    <th>{{__('RTL')}}</th>
                    <th class="text-center">{{__('Action')}}</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($languages as $language)
                  <tr>
                    <td>{{$language->id}}</td>
                    <td>{!! $language->name !!}</td>
                    <td>{{$language->code}}</td>
                    <td>{{$language->rtl? __('Yes') : __('No')}}</td>
                    <td class="text-center">
                      <a data-toggle="tooltip" data-placement="bottom" title="Edit lang Name & Flag" href="{{route('languages.edit' ,$language->id )}}" class="btn btn-primary bg_primary btn-sm"><i
                          class="fa fa-edit"></i></a>
                      <a data-toggle="tooltip" data-placement="top" title="Edit translations" href="{{route('languages.show' ,$language->id )}}" class="btn btn-info  btn-sm">
                        <i class="fas fa-spell-check"></i></a>
                      <button class="btn btn-danger bg_danger btn-sm confirm" id="{{$language->id}}">
                        <i class="fa fa-trash"></i>
                      </button>
                      <form id="delete{{$language->id}}" action="{{route('languages.destroy' ,$language->id ) }}"
                        method="POST" class="d-none">
                        @csrf
                        @method("DELETE")
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="LanguageModal" tabindex="-1" role="dialog" aria-labelledby="LanguageModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="LanguageModalLabel">{{__('Create New Language')}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" action="{{route('languages.store')}}">
        <div class="modal-body">
          @csrf
          <div class="mb-3">
            <label class="form-label">{{ __('Name') }} :</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
              value="{{ old('name') }}" required placeholder='Name'>
            @error('name')
            <div class="invalid-feedback">
              <strong>{{ $message }}</strong>
            </div>
            @enderror
          </div>
          <div class="mb-3">
            <label class="form-label">{{ __('Languages') }}</label>

            <select class="selectpicker  @error('code') is-invalid @enderror" required name="code"
              data-live-search="true" data-width="100%">
              @foreach(\File::files('assets/flags') as $path)

              @if(!in_array(pathinfo($path)['filename'],$lang))

              <option value="{{ pathinfo($path)['filename'] }}" data-content="<div class=''><img src='{{ asset('assets/flags/'.pathinfo($path)['filename'].'.png') }}' 
                class='mr-2 flag_img'><span>{{ pathinfo($path)['filename'] }}</span></div>"></option>

              @endif
              @endforeach
            </select>
            @error('code')
            <div class="invalid-feedback">
              <strong>{{ $message }}</strong>
            </div>
            @enderror
          </div>
          <div class="row align-items-center">
            <label for="site-title" class="form-control-label col-sm-3 ">{{__('RTL')}}</label>
            <div class="col-sm-6 col-md-9">
              <label class="custom-switch text-md-right">
                <input type="checkbox" name="rtl" class="custom-switch-input" value="1">
                <span class="custom-switch-indicator"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('Close')}}</button>
          <button type="submit" class="btn btn-primary">{{__('Add New Language')}}</button>
        </div>
      </form>
    </div>
  </div>
</div>

@endsection

@if ($errors->any())
@push('scripts')
<script src="{{ asset('assets/js/vendor/open-modal.js') }}"></script>
@endpush
@endif


@push('styles')
<link href="{{ asset('assets/css/selectric.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
<link href="{{ asset('assets/css/select.bootstrap4.min.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('assets/css/bootstrap-select.min.css') }}">
@endpush


@push('libraies')
<script src="{{ asset('assets/js/vendor/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/select.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/jquery.selectric.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/bootstrap-select.min.js') }}"></script>
@endpush

@push('scripts')
<script src="{{ asset('assets/js/vendor/modules-datatables.js') }}"></script>
@endpush